### ISSUE TITLE
Some errors when running the code

### ISSUE THREAD

**Issue by woaipichuli** [inoryy/reaver#3]
I have received some errors when running the code. But I don't know why this happens.

Process Process-1:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\multiprocessing\process.py", line 252, in _bootstrap
    self.run()
  File "C:\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "E:\liupenghui\pysc2-rl-agent-master\common\env.py", line 22, in worker
    env = env_fn_wrapper.x()
  File "E:\liupenghui\pysc2-rl-agent-master\common\env.py", line 14, in _thunk
    env = sc2_env.SC2Env(**params)
  File "C:\Anaconda3\lib\site-packages\pysc2\env\sc2_env.py", line 132, in __init__
    self._setup((agent_race, bot_race, difficulty), **kwargs)
  File "C:\Anaconda3\lib\site-packages\pysc2\env\sc2_env.py", line 173, in _setup
    self._run_config = run_configs.get()
  File "C:\Anaconda3\lib\site-packages\pysc2\run_configs\__init__.py", line 38, in get
    if FLAGS.sc2_run_config is None:  # Find the highest priority as default.
  File "C:\Anaconda3\lib\site-packages\absl\flags\_flagvalues.py", line 488, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --sc2_run_config before flags were parsed.

**Comment by inoryy** [comment]
Seems like pysc2 version mismatch, which one are you using?
